### ISSUE TITLE
Broken Url?

### ISSUE THREAD

**Issue by engineswap** [walmat/link-builder#2]
When using your given url, it seems to be broken (keep in mind im using my own id) 
![image](https://user-images.githubusercontent.com/38859788/41793134-cb0825a4-7620-11e8-95e7-660151f9968a.png)

**Comment by walmat** [comment]
URL should be fine. Have you clicked the `Create a Bot User` near the bottom of the page first?

@IlyaTataurov

**Comment by engineswap** [comment]
That did the trick, thanks as always:)
